source "https://rubygems.org"

gem "jekyll-github-metadata"
gem "jekyll-text-theme"
gem "github-pages", "~> 228", group: :jekyll_plugins
group :jekyll_plugins do
    gem "jekyll-feed", "~> 0.12"
  end
  gem "webrick", "~> 1.7"